# Generated by Django 5.0.4 on 2024-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='total_copies_sold',
            field=models.IntegerField(default=0),
        ),
    ]
