# Generated by Django 5.0.4 on 2024-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_game_description_game_developer_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='total_copies_sold',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
