# Generated by Django 5.0.4 on 2024-05-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_game_total_copies_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
